project_id = "hbkptilrqqsqjlkabpbe"

[functions.chatbot]
verify_jwt = true

[functions.setup-2fa]
verify_jwt = false

[functions.verify-2fa]
verify_jwt = false

[functions.disable-2fa]
verify_jwt = false

[functions.ai-studio]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.log-error]
verify_jwt = true

[functions.initiate-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.send-donation-email]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = true

[functions.verify-login-2fa]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.set-user-role]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.send-onesignal-notification]
verify_jwt = false
